services:
  - type: web
    name: eco-urban
    env: node
    buildCommand: npm install; npm run build
    startCommand: npm run dev
    plan: free
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://tagleseanandrei:QsIO8e1RvPqDDpwS@cluster0.tphbs0m.mongodb.net/test?retryWrites=true&w=majority
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production