services:
  - type: web
    name: eco-urban
    env: node
    buildCommand: npm install --production=false && npm run build
    startCommand: node index.js
    plan: free
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://tagleseanandrei:QsIO8e1RvPqDDpwS@cluster0.tphbs0m.mongodb.net/test?retryWrites=true&w=majority
      - key: NODE_ENV
        value: production